### PR TITLE
Updated yarn.lock, use try_getUnderlyingPrice

### LINKED ISSUE #15: Indexing error on subgraph
Hello! The subgraph had an indexing error https://thegraph.com/hosted-service/subgraph/graphprotocol/compound-v2 and was reported to us (@rotki). Unfortunatly we don't have more information that what is provided in the response

```
{
  "errors": [
    {
      "message": "indexing_error",
      "locations": [
        {
          "line": 2,
          "column": 2
        }
      ],
      "path": [
        "mintEvents"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "errors": [
            {
              "message": "indexing_error",
              "locations": [],
              "path": [
                "mintEvents"
              ]
            }
          ]
        }
      }
    }
  ],
  "data": null
}
```

### PR DESCRIPTION
**Pull request by juanmardefago**
Could potentially fix #15. Changes the uses of `getUnderlyingPrice` to a safe call with `try_getUnderlyingPrice`.

We will need to restart the js wrappers after merging and deploying.

### CODE REVIEW

**Comment by ghostry** [comment]
```
ERRO Handler skipped due to execution failure, error: attempted to divide BigDecimal `2` by zero	wasm backtrace:	    0: 0x1051 - <unknown>!<wasm function 36>	    1: 0x284c - <unknown>!<wasm function 165>	    2: 0x2aca - <unknown>!<wasm function 168>	, handler: handleTransfer, block_hash: 0x5f469457371b974f86cc99689c3558d111b56120298f3d7ca07317d34b13ab5c, block_number: 13364303, sgd: 1, subgraph_id: QmT8REdioaAoLYep453coxfDDFhGniBwE8k14pUMSPcUjB, component: SubgraphInstanceManager
```

**Comment by juanmardefago** [comment]
@ghostry did you run the code in your own infrastructure and got that error?

**Comment by ghostry** [comment]
> @ghostry did you run the code in your own infrastructure and got that error?

The issue of the contract is already okay.

**Comment by cwang25** [comment]
Hi it seems this fix might help on unblocking the current subgraph blockage. 
Can you check-in the code changes ?

(I tried a bit on my subgraph studio, and found several other functions are also needed to wrap with try_ in order to unblock.) 

Since this PR is 20+ days ago, not sure if it's still active here. 
I have also created a PR #17 that included other fixes so at least the compound v2 subgraph can be unblocked. 


Thanks

**Comment by juanmardefago** [comment]
this code is deployed on my own subgraph as a workaround (https://thegraph.com/hosted-service/subgraph/juanmardefago/compound-v2) but ideally should be merged to the original one.

There might be additional places where `try_` functions should be used (which I think you probably take care on your PR), this fix was mostly focused to the actual one that made the subgraph break, since it was meant as a fast patch to make sure some apps kept on working.

Feel free to continue with your PR, I'm quite sure there are other possible failure points which you might cover there :)

**Pull request merged**
